### ISSUE TITLE
My article about your package 

### ISSUE THREAD

**Issue by tirthajyoti** [pdpipe/pdpipe#10]
Hi,

I found your package quite useful and pretty neat. I may contribute to it later with ideas and suggestions for enhancement.

For now, I have written an article about it and it has gained traction pretty fast.

**[Check out the article here](https://towardsdatascience.com/build-pipelines-with-pandas-using-pdpipe-cade6128cd31)**.

**Comment by shaypal5** [comment]
@tirthajyoti, this is awesome! Actually a friend shared it with me yesterday, and I just finished going through it. Great stuff, man. I'm so happy you found this little thing useful. Contributions are more than welcomed. :)

Like I mentioned in my comment to the article, I'd love it if you be willing to link to the project repository itself a few times over the course of the article, so more people get here, perhaps star the repo and see the documentation. I think this can help it spread, which my drive contributions and make it even better! :)

Cheers,
Shay

**Comment by tirthajyoti** [comment]
I linked this Repo on all the places the word `pdpipe` is mentioned in the article.

Please feel free to give a link to my article in your Readme or anywhere you like.

**Comment by shaypal5** [comment]
Thanks! Will do!

**Comment by shaypal5** [comment]
Can I get a friends link, so I'm sure anyone who wants to rely on this as a tutorial can indeed read your article?

**Comment by tirthajyoti** [comment]
Instead of Medium article, I can create a Markdown and either host it on my Github.io or in the project itself. Give me a few days for that.

**Comment by shaypal5** [comment]
Sounds good! :)

**Comment by shaypal5** [comment]
Hey @tirthajyoti 

I've added the `RowDrop` stage to `pdpipe` in the latest release, `v0.0.33`, which can solve one of the more complex operations in your blog post in a single pipeline stage. Instead of three stages, you can remove all rows for which the price is smaller or equal to 250000 by using the following stage:
```pdp.RowDrop({'Price': lambda x: x <= 250000})```

If you don't mind, I'd love for you to update the blog post, so the cleaner solution is presented.

Thanks!
Shay

**Comment by tirthajyoti** [comment]
OK, @shaypal5 I will test it in my Notebook and add as an update to my article.
I have been out this whole week on business travel, so will get to it next week.

**Comment by shaypal5** [comment]
Cool! Waiting for an update...

**Comment by tirthajyoti** [comment]
Hey @shaypal5 , I updated the article on Medium and also created the Free Markdown version so that users can refer there. It is hosted on my Github.io page and **[here is the link](https://tirthajyoti.github.io/Notebooks/Pandas-pipeline-with-pdpipe)**.

**Comment by shaypal5** [comment]
Thanks, man! :)

Can I bother you again? I've created a simple homepage for the package:
https://pdpipe.github.io/pdpipe/

Would you mind updating the links in the article to point to the homepage instead of the repository? I think it's way more friendly to newcomers.

**Comment by shaypal5** [comment]
Also, the hyperlink on my name doesn't work, and I'd love it to point to [my personal website](http://www.shaypalachy.com/) anyway, is possible. Thanks!

(My personal address: http://www.shaypalachy.com/)

![image](https://user-images.githubusercontent.com/917954/71380112-c1a0ee80-25d6-11ea-9195-80992877e899.png)

**Comment by tirthajyoti** [comment]
Updated these links now.

**Comment by shaypal5** [comment]
Thanks :)
