### ISSUE TITLE
exclude_columns does not work for ColumnsBasedPipelineStage

### ISSUE THREAD

**Issue by jjlee88** [pdpipe/pdpipe#100]
When setting `exclude_columns` as a list of strings in the constructor of `ColumnsBasedPipelineStage` the member variable `self._exclude_columns` is set to a tuple instead of the passed in list. This leads to errors with `__get_cols_by_arg` which ends up returning the tuple and not the list itself.  

## Code where the issue appears to be

https://github.com/pdpipe/pdpipe/blob/763320db326e9a49f51bd7fb9ea65944f51869f2/pdpipe/core.py#L602

The line which seems incorrect is linked above. `_interpret_columns_param` returns a tuple, so we should be assigning the individual components of the tuple, in that line, as opposed to assigning the entire return value to 'self._exclude_columns'; something like 

`self._exclude_columns, _ = self._interpret_columns_param(...`

**Comment by shaypal5** [comment]
Right you are! Thank you for catching this!

I'll fix this and add a text.

It shouldn't be discarded, by the way. The second element is an ``str`` representation of the columns to be discarded. It will be used to construct the pipeline description string.

**Comment by shaypal5** [comment]
Done. The new test now catches this error:
https://github.com/pdpipe/pdpipe/actions/runs/2313073586

And the same test passes for the fix:
https://github.com/pdpipe/pdpipe/actions/runs/2313093564

**Comment by shaypal5** [comment]
No problem! I wrote it for fun, and it's an immense pleasure to have other people find use for it.
