### ISSUE TITLE
Switch from pdoc3 to pdoc?

### ISSUE THREAD

**Issue by milesgranger** [pdpipe/pdpipe#102]
Would you be interested in switching from pdoc3 to [pdoc](https://github.com/mitmproxy/pdoc), specifically due to [this point here](https://github.com/mitmproxy/pdoc#pdoc-vs-pdoc3)? Seems to be more actively maintained as well.

**Comment by shaypal5** [comment]
Oh, actually it's the old doc site that was built using `pdoc3` (and is configured through the `apidoc` dir).

The new one can be found in:
https://pdpipe.readthedocs.io/en/latest/

It is built using `mkdocstrings`, and configured via the `docs` dir and some additional configuration files in the repository's root.

I've deleted the `apidoc` directory as it's no longer required, and to avoid further confusion.

Thank you! :)
