### ISSUE TITLE
Doc Site: Class docstring examples are not presented correctly

### ISSUE THREAD

**Issue by shaypal5** [pdpipe/pdpipe#104]
On [the project's docsite](https://pdpipe.readthedocs.io/en/latest/), class docstring examples are not presented correctly.

I'm pretty sure this is the last inheritance from `pydoc3`, the way the doc site was compiled before, which required extra indentation of the `Example` portion of docstring to compile. Removing the indent should solve this.

## Expected Result

Nice, syntax-highlighted, code example.

## Actual Result

See for example:
https://pdpipe.readthedocs.io/en/latest/reference/sklearn/#pdpipe.sklearn_stages.Scale

<img width="674" alt="image" src="https://user-images.githubusercontent.com/917954/177029723-41147e5a-e140-4ab0-a51c-734666ff438a.png">

**Comment by DavidKatz-il** [comment]
I don't see any problem, it looks good to me.   

![image](https://user-images.githubusercontent.com/41651296/205480716-1963afff-f4af-4581-97e7-3b857b9338a1.png)

**Comment by shaypal5** [comment]
You're right, I've fixed all of it in one of my doc site work sessions. Thank! :)
