### ISSUE TITLE
Feature Request: Dynamic params from input dataframe on fit_transform

### ISSUE THREAD

**Issue by shaypal5** [pdpipe/pdpipe#110]
I want a way to supply pipeline stage constructor parameters with future-like placeholders, so that actual values will be determined by prior stages on application time.

I would assign the name of the future `ApplicationContext` key holding the value after it was calculated — wrapped by a unique class — to the parameter.

The constructor will hold on to this object, and will — in application time — pull the value of the right key from either the fit context or the application context (depending on how I set it: I might want this value to be set on pipeline fit, or to be set on each application dynamically, even on transforms when the pipeline is fitted), and use it for the transformation. Default should probably be the fit context?

Here's an example:

```python
import numpy as np; import pandas as pd; import pdpipe as pdp;

def scaling_decider(X: pd.DataFrame) -> str:
    """Determines with type of scaling to apply by examining all numerical columns."""
    numX = X.select_dtypes(include=np.number)
    for col in numX.columns:
        # this is nonsense logic, just an example
        if np.std(numX[col]) > 2 * np.mean(numX[col]):
            return 'StandardScaler'
    return 'MinMaxScaler'

pipeline = pdp.PdPipeline(stages=[
    pdp.ColDrop(pdp.cq.StartWith('n_'),
    pdp.Scale(
        # fit=False means it will take it from the application context, and not fit context
        scaler=pdp.dynamic(scaling_decider, fit=False),  
        joint=True,
    ),
])
```

## Design

This has to be implemented at the `PdPipeline` base class. Since the base class can't hijack constructor arguments, I think the contract with extending classes should be:

1. When implementing class exteding `PdPipeline`, if you want to enjoy support for contextual constructor parameters, you **MUST** delay any initialization of inner state objects to `fit_transform`, so that fit/application context is available on initialization (it is NOT available at pipeline stage costruction and initialization, after all).

2. `pdp.contextual` is a factory function that returns contextual parameter placeholder objects. Code using it shouldn't really care about it, as it should never interact with the resulting objects directly. I think.

3. `PdPipeline` can auto-magically make sure that any attribute of a `PdPipeline` instance that is assigned a `pdp.contextual` object in the constructor (e.g. `self.k = k`, and the `k` constructor argument was provided with `k=pdp.future('pca_k')`) will be hot-swapped with a concrete value by the time we wish to use it `fit_transform` or `transform` (for example, when we call `self.pca_ = PCA(k=self.k)`). It can also do so for any such object that is contained in any iterable or dict-like attribute (so if I have `self._pca_kwargs = {...}` in my constructor, I can safely call `self.pca_ = PCA(**self._pca_kwargs)` in `fit_transform()`.

## Implementation thoughts

To make this efficient, since this means accessing sub-class attribute instance on pipeline transformations, I have a few thoughts:

1. The `contextuals` module should have a global variable such as `CONTEXTUALS_ARE_ON = False`. Then, the `pdp.contextual` factory function sets `global CONTEXTUALS_ARE_ON; CONTEXTUALS_ARE_ON = True` when called. Then, we condition the whole inspection-heavy logic on this indicator variable, so that if our user never called `pdp.contextual` during the current kernel, runtime is saved.

2. I first thought `pdp.contextual` could somehow register `_ContextualParam` objects in a registery we could use to find what needed to be swapped, but actually this wouldn't help, as they won't know which attribute of which pipeline stage they were assigned to.

3. We thus have to scan sub-class attributes, but we can do so **if and only** after `pdp.contextual` was called, and right after pipeline stage initialization. Moreover, we can create a literal list of all attribute names we should ignore, stored in `pdpipe.core` as a global: e.g. `_IGNORE_PDPSTAGE_ATT = ['_desc', '_name']`, etc. Everything we know isn't an attribute the sub-class declared. Then, we can check any attribute that isn't one of these. This can be done in `pdpipe.PdPipelineStage.__init__()`, since it's called (by contract; we can demand that from extending subclasses) at the end of the `__init__()` method of subclasses. When we find that such an attribute holds a `pdp.contextual`, we register it at the `pdp.contextuals` module, in some global dict (or something more sophisticated), keyed by the attribute name. We can also registed the containig stage object.

Then, in a stage `fit_transform` and `transform` methods, if the current stage object is registered for contextual hot-swapping, we find the concrete contextual value of any attribute resigtered for this stage (in either the `self.fit_context` object or `self.application_context` object the pipeline injects all stages during applications of the pipeline) and hot-swap it literaly: This will look something like `setattr(self, 'k', self.fit_context['pca_k'])`, since we're at `pdpipe.PdPipelineStage.fit_transform()`, and the `self` object is an instance of the subclass requiring the hot swap (in this case, `pdp.Decompose`).

**Comment by shaypal5** [comment]
Reference pseudo-code for the `pipeline.fit_transform()`:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/917954/183242129-6ef77f64-37c6-4f47-ba76-94f6c31e3acd.png">

**Comment by amihaiOff** [comment]
# Implementation thoughts after meeting 6/8 
In the stage init, when is calls `super().__init__` the super looks to see if it gets a dynamic type for one of it's non standard attrs (or looks for an `is_dynamic` flag) and if so populates a list of dymanics (or contextuals) with a dict with the name of the attr that is dynamic and the callable that sets the value at "fit time". 
Then in the pipeline, when going through the stages to do fit_transform, the pipeline will go through this list and apply the callable to the relevant attr name (see code ref above). 
This also means we don't need a global as first thought which can be problematic with more than one pipeline instance. 
The `pdp.dynamic` is mainly meant as a wrapper around the given callable (do we want to assert the input is a callable? @shaypal5) to be give it a specific type to be easily marked as a dynamic attr. Therefore the `pdp.dynamic`  factory will return a `Dynamic` object with the callable inside (and can perform checks for validity). The call of the Dynamic will call the inner callable. 
Also, don't forget to add the dynamic to package level namespace.

**Comment by shaypal5** [comment]
1. Looks good! Thank you for writing this down! :)

2. No, I don't think we want to assert the argument is indeed a callable. When calling it, we should `try-except` and throw a `ValueError` at the user if calling fails; it will fail with a `TypeError`, and we would also have to check the text "is not callable" is contained in the message. See, for example, such a usecase in `pdpipe.PdPipelineStage._compound_prec`:

```python
    _POS_ARG_MISMTCH_PAT = re.compile(
        r'\d positional argument[s]? but \d (were|was) given')

    _MISSING_POS_ARG_PAT = re.compile(
        r'missing \d+ required positional argument')

    def _compound_prec(
        self,
        X: pandas.DataFrame,
        y: Optional[pandas.Series] = None,
        fit: Optional[bool] = False,
    ) -> bool:
        if self._prec_arg:
            to_call = self._prec_arg
            if fit:
                try:
                    to_call = self._prec_arg.fit_transform
                except AttributeError:
                    pass
            try:
                return to_call(X, y)
            except TypeError as e:
                if len(PdPipelineStage._POS_ARG_MISMTCH_PAT.findall(
                        str(e))) > 0:
                    return to_call(X)
                raise e  # pragma: no cover

        # now, do the same for the _prec abstractmethod, so as to support
        # implementations only including X in their signature
        if y is None:
            try:
                return self._prec(X)
            except TypeError as e:
                if len(PdPipelineStage._MISSING_POS_ARG_PAT.findall(
                        str(e))) > 0:
                    # self._prec is hopefully expecting y
                    return self._prec(X, y)
                raise e
        try:
            return self._prec(X, y)
        except TypeError as e:
            if len(PdPipelineStage._POS_ARG_MISMTCH_PAT.findall(str(e))) > 0:
                return self._prec(X)
            raise e  # pragma: no cover
```

3. Also, remember all `Dynamic` and `Contextual` objects should be fitable; they should have a `self.is_fitted` state (or something similar), and should have a `fit_transform` and `transform` wrapper methods. The `fit_transform` method actually calls the contained `callable`, saves the result and returns it; the `transform` method just returns the saved result. The pipeline object using this API to inject dynamic attributes/parameters to composing pipeline stages should call the right method according to context (depending if it itself is being fit-transformed or transformed). You have two reference implementations for this kind of objects: `cq.ColumnQualifier`, and `cond.Condition`.
