### ISSUE TITLE
Feature Request: More information in the messages of PipelineApplicationError

### ISSUE THREAD

**Issue by shaypal5** [pdpipe/pdpipe#27]
At the moment, there is too little information in the messages of PipelineApplicationError.

Things that should be added:
1. The type of the pipeline stage (so the name of the class).
1.1. Actually, maybe the description?! :)
2. The index in the pipeline (obviously only when part of a pipeline; requires catching and rethrowing at the pipeline level).
3. The label of the pipeline stage, when #19 is implemented.

**Comment by isaeef** [comment]
@shaypal5  I would like to work on this issue

**Comment by shaypal5** [comment]
That's great! Go ahead. :)

**Comment by naveenkaushik2504** [comment]
I'd like to work on this issue. Have gone through the code to make the necessary changes. Will submit a PR soon. Hope this functionality is still desired.

**Comment by shaypal5** [comment]
Great! Yeah, I'm still waiting for it. :)

**Comment by shaypal5** [comment]
Close with #38 !
Hooray @naveenkaushik2504 !
