### ISSUE TITLE
Improve the docs

### ISSUE THREAD

**Issue by gandad** [pdpipe/pdpipe#28]
Excellent work! I love this tool very much.
I think you can improve the docs.
I tried some times to know how to use AdHocStage to  do sum/mean operations. 
The description of AggByCols is worse.

Please provide some basic information about your system (Python version,
operating system, &c).

**Comment by pjakobsen** [comment]
I would like to help with documentation, but I need more info.  For example, how do I add multiple conditions to RowDrop as advertised in docs?   And, for example, how do I use RowDrop to remove every row that has column "Country" values that starts with "Europe" preferable using lamda expression without regex!  :)   This is a very common ETL operation, removing rows with string matching.

**Comment by marctorsoc** [comment]
related to this, I think a great and easy improvement would be to have links to each of the pipes here https://pdpipe.github.io/pdpipe/doc/pdpipe/#basic-stages

**Comment by yarkhinephyo** [comment]
Hi! I can try to add the suggestions above to the documentation

**Comment by shaypal5** [comment]
Have a go at it!

You can look at the tests for the aforementioned stages for help on other uses for them.

Also ask me for help if you need it.

And please - any use case you add documentation for, add a basic test for in the test suites of the corresponding stage; whatever we publish the package can do, we MUST test for.

Good luck! :)

**Comment by shaypal5** [comment]
See PR #65 .

**Comment by shaypal5** [comment]
Btw @yarkhinephyo , that's another way for you to add docs to the package. :)

**Comment by shaypal5** [comment]
Closing this as the doc site now includes a fair amount of nice tutorials.
