### ISSUE TITLE
The Performance is very poor

### ISSUE THREAD

**Issue by gandad** [pdpipe/pdpipe#29]
the record count is 74000.
## The following code is using pdpipe:
--------------------------------------------------------------------------
start = time.time()
salesdata = pd.read_csv(fg_generator["dataPath"]+"/processed_salesdata.csv")
salesdata = pdp.PdPipeline([
    pdp.Schematize("SKC,日期,销量,销售金额,客流,加购,活动级别,S,A,B,N,上柜日期,季节结束,品类组,品类,原始价,季节".split(",")),
    pdp.ApplyByCols("品类组",lambda x: "上装" if x=="上装" else "其它"),
    pdp.ApplyByCols(["日期","上柜日期","季节结束"],pd.to_datetime),
    pdp.ApplyToRows(lambda row:pd.Series({
        "标准金额":row["原始价"]*row["销量"],
        "销售折扣":0 if row["原始价"]*row["销量"]<=0 else row["销售金额"]/(row["原始价"]*row["销量"]),
        "周":int(row["日期"].strftime('%W')),
        "上柜天数":(row["日期"]-row["上柜日期"])/np.timedelta64(1, 'D'),
        "生命周期":(row["季节结束"]-row["上柜日期"])/np.timedelta64(1, 'D'),
        "C1": 1 if row["品类组"]=="上装" else 0,
        "C2": 1 if row["品类组"]=="其它" else 0,
        "销量":0 if row["销量"]<0 else row["销量"],
        "客流":0 if row["客流"]<0 else row["客流"],
        "加购":0 if row["加购"]<0 else row["加购"]
    })),
    pdp.AdHocStage(lambda df:df[df["上柜天数"]<=df["生命周期"]]),
    pdp.ColDrop("活动级别")
]).apply(salesdata,verbose=True, exraise=True)

salesdata_cumitems=salesdata[["SKC","日期","销量","客流","加购"]].sort_values(by=["SKC","日期"]).groupby(['SKC']).cumsum()
salesdata_cumitems.columns=["累计销量","累计客流","累计加购"]
salesdata["累计销量"] = salesdata_cumitems["累计销量"]
salesdata["累计客流"] = salesdata_cumitems["累计客流"]
salesdata["累计加购"] = salesdata_cumitems["累计加购"]
print("consumed time(s)=",time.time()-start)

### The result is:
- Transform input dataframes to the following schema: SKC, 日期, 销量, 销售金额,
  客流, 加购, 活动级别, S, A, B, N, 上柜日期, 季节结束, 品类组, 品类, 原始价, 季节..
- Apply a function  to columns 品类组..
- Apply a function  to columns 日期, 上柜日期, 季节结束..
- Generating a column with a function ...
- A pipeline stage...
- Drop columns 活动级别..
consumed time(s)= 102.63764142990112

## The following code is raw pandas:
--------------------------------------------------------------------------
start = time.time()
salesdata = pd.read_csv(fg_generator["dataPath"]+"/processed_salesdata.csv")
salesdata=salesdata["SKC,日期,销量,销售金额,客流,加购,活动级别,S,A,B,N,上柜日期,季节结束,品类组,品类,原始价,季节".split(",")]

salesdata["日期"]=pd.to_datetime(salesdata['日期'])
salesdata["上柜日期"]=pd.to_datetime(salesdata['上柜日期'])
salesdata["季节结束"]=pd.to_datetime(salesdata['季节结束'])
salesdata["周"]=salesdata["日期"].apply(lambda x: int(x.strftime('%W')))

salesdata["品类组"] = salesdata["品类组"].apply(lambda x: "上装" if x=="上装" else "其它")
salesdata["C1"] = salesdata["品类组"].apply(lambda x: 1 if x=="上装" else 0)
salesdata["C2"] = salesdata["品类组"].apply(lambda x: 1 if x=="其它" else 0)
#salesdata["C2"] = salesdata["品类组"].apply(lambda x: 1 if x=="下装" else 0)
#salesdata["C3"] = salesdata["品类组"].apply(lambda x: 1 if x=="套装" else 0)

salesdata["标准金额"] = salesdata["原始价"]*salesdata["销量"]
salesdata["销售折扣"]=salesdata["销售金额"]/salesdata["标准金额"]
salesdata.loc[salesdata["销售折扣"].isna(),"销售折扣"]=0

salesdata.loc[salesdata["销量"]<0,"销量"]=0
salesdata.loc[salesdata["客流"]<0,"客流"]=0
salesdata.loc[salesdata["加购"]<0,"加购"]=0

salesdata["上柜天数"]=(salesdata["日期"]-salesdata["上柜日期"])/np.timedelta64(1, 'D')
salesdata["生命周期"]=(salesdata["季节结束"]-salesdata["上柜日期"])/np.timedelta64(1, 'D')
salesdata = salesdata[salesdata["上柜天数"]<=salesdata["生命周期"]]

salesdata_cumitems=salesdata[["SKC","日期","销量","客流","加购"]].sort_values(by=["SKC","日期"]).groupby(['SKC']).cumsum()
salesdata_cumitems.columns=["累计销量","累计客流","累计加购"]
salesdata["累计销量"] = salesdata_cumitems["累计销量"]
salesdata["累计客流"] = salesdata_cumitems["累计客流"]
salesdata["累计加购"] = salesdata_cumitems["累计加购"]
print("consumed time=",time.time()-start)

### The result is:
consumed time= 1.107456922531128

--------------------------------------------------------------------------
So,pdpipe is 100X slower than the pandas way.
did I use pdpipe in the right way?

**Comment by shaypal5** [comment]
Hey @gandad ,

Nope, you seem to be using `pdpipe` right. I never encountered such a difference so far.
I'd love to investigate it, to understand where the performance difference is coming from.

Can you share the CSV you're using? Or maybe reproduce this on some data that you can share? Then I can run it on my end and start investigating the different stage; there is obviously something my code is doing wrong, or some kind of missing functionality.

**Comment by gandad** [comment]
Thanks for your replay.
I have attached the CSV and the python code.
The running platform is Win10+Python3.73+Intel i7-9750H+RAM32G




using pdp...
- Transform input dataframes to the following schema: SKC, 日期, 销量, 销售金额,
&nbsp; 客流, 加购, 活动级别, S, A, B, N, 上柜日期, 季节结束, 品类组, 品类, 原始价, 季节..
- Apply a function&nbsp; to columns 品类组..
- Apply a function&nbsp; to columns 日期, 上柜日期, 季节结束..
- Generating a column with a function ...
- A pipeline stage...
- Drop columns 活动级别..
consumed time(s)= 106.0992021560669
using the original way...
consumed time= 1.1559741497039795



------------------ 原始邮件 ------------------
发件人:&nbsp;"Shay Palachy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 晚上8:00
收件人:&nbsp;"pdpipe/pdpipe"<pdpipe@noreply.github.com&gt;;
抄送:&nbsp;"王书昌"<yes2us@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pdpipe/pdpipe] The Performance is very poor (#29)




Hey @gandad ,
 
Nope, you seem to be using pdpipe right. I never encountered such a difference so far.
 I'd love to investigate it, to understand where the performance difference is coming from.
 
Can you share the CSV you're using? Or maybe reproduce this on some data that you can share? Then I can run it on my end and start investigating the different stage; there is obviously something my code is doing wrong, or some kind of missing functionality.

**Comment by shaypal5** [comment]
Hey @gandad , 

I can't find the CSV file you have mentioned... :)

**Comment by shaypal5** [comment]
Taking a better look at your code, it's obvious you've chosen much much heavier and inefficient implementations to the same operations in `pdpipe`. Most have a better way to write in `pdpipe`, and those that do not should definitely get one.

I'm closing this as I can't really investigate this without your data, but if you ever upload this I'd love for you to re-open the issue and we can work out the operations one-by-one, and add anything that's missing.

Cheers! :)
