### ISSUE TITLE
RowDrop with True  not dropping rows

### ISSUE THREAD

**Issue by pjakobsen** [pdpipe/pdpipe#30]
I wish to drop every row with GEO column containing the string European.   For example:

_"European Union - 27 countries (from 2020)"_  should be dropped.  So I use

`pdp.RowDrop({'GEO': lambda x: str(x).find('European')})`

All rows containing "European" should be dropped, but instead I get only rows containing those values.  See code below

`

  | TIME | GEO | Value
1990 | European Union - 27 countries (from 2020) | 443.981
1990 | European Union - 28 countries (2013-2020) | 453.981
1991 | European Union - 27 countries (from 2020) | 613.859
1991 | European Union - 28 countries (2013-2020) | 627.859
1992 | European Union - 27 countries (from 2020) | 812.449
1992 | European Union - 28 countries (2013-2020) | 862.449
1993 | European Union - 27 countries (from 2020) | 1,070.599
1993 | European Union - 28 countries (2013-2020) | 1,201.599
1994 | European Union - 27 countries (from 2020) | 1,473.737
1994 | European Union - 28 countries (2013-2020) | 1,626.737
1995 | European Union - 27 countries (from 2020) | 2,230.999
1995 | European Union - 28 countries (2013-2020) | 2,430.999
1996 | European Union - 27 countries (from 2020) | 3,115.721
1996 | European Union - 28 countries (2013-2020) | 3,353.721

`

```
import pdpipe as pdp
#  Creat some tasks without executing them
pipeline = pdp.ColDrop(['SIEC', 'PLANT_TEC', 'UNIT'])
pipeline+=pdp.RowDrop({'Value': lambda x: x ==':'})
pipeline+=pdp.RowDrop({'GEO': lambda x: str(x).find('European')})
# Now send add this tasks in a pipeline
df = pipeline(df)

#data = data.drop(columns=['SIEC', 'PLANT_TEC', 'UNIT'])
#data.pd.rename(columns = {'test':'TEST'}, inplace = True) 
df.head(30)

```

**Comment by pjakobsen** [comment]
Sorry, I made a bad programming blunder.  I should have been 

`pdp.RowDrop({'GEO': lambda x: str(x).find('European')==0})`

**Comment by shaypal5** [comment]
No problem :)
