### ISSUE TITLE
Apply a function to multiple columns

### ISSUE THREAD

**Issue by easimadi** [pdpipe/pdpipe#37]
Summary.

## Expected Result

I am not able to apply a pipeline with a function to transform multiple columns
```
def a_function(a,b):
     use a and b

pipeline = pdp.ApplyByCols(columns = ["df_col1","df_col2"],func=email_transform, result_columns = ["name_col1","name_col2"], drop = False)
```

I get the error
a_function() missing 1 required positional argument: 'b'

**Comment by DavidKatz-il** [comment]
To apply a function on multiple columns you need to write a function that recives only one column.

```python
def foo(column: pd.Series) -> pd.Series:
    # do something with your column

pipeline = pdp.ApplyByCols(
    columns=["col1", "col2"],
    func=foo,
    result_columns=["new_col1", "new_col2"],
    drop=False
)
...
```

**Comment by shaypal5** [comment]
What David said!

Columns-wise transformations are applied with `ApplyByCols`, while generating a column (or several columns) from existing columns is done with `ApplyByRows`.
