### ISSUE TITLE
Dependency on sklearn

### ISSUE THREAD

**Issue by Silun** [pdpipe/pdpipe#43]
It appears that `pdpipe` is dependent on [sklearn](https://pypi.org/project/sklearn/), the PyPI page of which plainly says not to use it and work with `scikit-learn` instead. Is there any chance you could switch the dependency to `scikit-learn` instead?

I was trying to add packages for `pdpipe` to Anaconda but I am running into trouble with `sklearn`, it's missing license etc. and came upon this issue in the process. I have already been adding `decore` and `strct`, but `sklearn` is harder to motivate since it both violates the license requirement and its maintainer plainly advises not to use it.

Edit: It seems I have misunderstood something about scikit-learn, the confusion was cleared up by someone else. Please disregard this issue, I'll close it.

**Comment by shaypal5** [comment]
Hey @Silun ,

Several clarifications:

1. First, the `sklearn` Python package is an optional requirement of `pdpipe`.

2. Secondly, the correct way to install the `sklearn` Python package is through the `scikit-learn` PyPI package. PyPI packages can and often do install Python packages (sometime more than one) with a different name than the name of the package on the Python Package Index. This is not unique to PyPI. Please note this distinction.

3. Thirdly, the one place that `pdpipe` does state this dependencies - in the `test` argument of `extra_requries`, to enable installing with `pip install pdpipe[test]` to get test dependencies - it is indeed given as `scikit-learn`, so I'm not even sure where did you find this wrong way to specify the dependency.

If you do find such a problem, please feel free to reopen this issue, but this time please link to the exact code line in the `setup.py` file where this is made (this is the one place when `pdpipe` dependencies are stated; if you find this is not so, please let me know).

Thank you, :)
Shay
