### ISSUE TITLE
Add example for GridSearchCV parameter tuning 

### ISSUE THREAD

**Issue by stefansimik** [pdpipe/pdpipe#57]
Hi, please add to documentation
simple example for common scenario in ML models,
how to use pdpipe with GridSearchCV.

It is not clear, how to do it / of if expected scenario at all.

This basic simple will help people to use pdpipe for all 
ML models and parameter-tuning techniques.

Best
Stefan

**Comment by shaypal5** [comment]
Good question. I'm working on it for the last couple of days.

I am not yet sure how easy it is to implement, as I think `sklearn` casts input dataframes to `numpy.ndarray` objects, but we'll see.

You can take a look at this branch if you want to:
https://github.com/pdpipe/pdpipe/tree/custpipebase

**Comment by stefansimik** [comment]
Excellent, thank you very much ❤️ 
I will test in my current project 👍

**Comment by shaypal5** [comment]
Great! Let me know how it goes.
