### ISSUE TITLE
Can't find the way to pass flags to RegexReplace

### ISSUE THREAD

**Issue by vecorro** [pdpipe/pdpipe#59]
Summary.

I wonder if is it possible to pass flags to the RegexReplace class to control de behavior of the regex engine.

## Expected Result

For instance, in the re module, you may pass to re.sub() flags like re.I to make the search case insensitive and re.M to search over strings that include the '\n' character. 

## Actual Result

After reading the documentation, I could not find how to do it.

## System Information

```

```

Please provide some basic information about your system (Python version,
operating system, &c).

Python 3.8, Pandas 1.3.4, pdpipe 0.0.63 

Thank you.

**Comment by shaypal5** [comment]
You're right. I'll add it ASAP and release a version in a couple of days. 
Good catch!

**Comment by shaypal5** [comment]
Amended in release `v0.0.64`: See the new `flags` constructor parameter for `RegexReplacer`.
Please reopen (or open a new issue) if problems arise. :)
