### ISSUE TITLE
Add time flag for PdPipeline.apply

### ISSUE THREAD

**Issue by yarkhinephyo** [pdpipe/pdpipe#62]
### Context
As mentioned in #40, currently there is a `time`  flag for `PdPipeline.fit_transform` and `PdPipeline.transform` which prints out the time taken for each stage of the pipeline. However, it does not exist for PdPipeline.apply yet.

### Proposed solution
Modify `PdPipeline.apply` to include `time` flag which it passes to `self.transform` and `self.fit_transform`.

**Comment by shaypal5** [comment]
Released in `v0.0.67`!!! <3

Way to go on your first contribution, @yarkhinephyo ! :)
