### ISSUE TITLE
About ColByFrameFunc

### ISSUE THREAD

**Issue by banduoba** [pdpipe/pdpipe#91]
Summary.

## Expected Result
**Execute add_Col function according to the condition of the df['A'] column value.**

What you expected.

## Actual Result
ERROR:PipelineApplicationError: Exception raised in stage [ 0] PdPipelineStage: Applying a function to generate column A.
What happened instead.
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/4811366/155849266-816fb1ba-a1c8-45ea-a781-a41d38270c55.png">
## Reproduction Steps

```python
import pdpipe as pdp
#%%
data = [[3, 3], [2, 4], [1, 5]]
df_usage = pd.DataFrame(data, [1,2,3], ["A","B"])

def add_Col(a,b):
    if a > 2:
        return a+ b
    else:
        return a+10

func = lambda df:add_Col(df['A'],df['B'])

pipeline = pdp.PdPipeline([
    pdp.ColByFrameFunc("A",func,follow_column='B'),
    pdp.ColRename({'A':'CloA','B':'ColB'})
])

df_usage = pipeline(df_usage,verbose=True)

```

## System Information
MacOS 10.15.7
python version:3.9.10

Please provide some basic information about your system (Python version,
operating system, &c).

**Comment by banduoba** [comment]
Actually I want to know if it is possible to generate new columns based on conditional judgments of multiple columns. Thank you.
@shaypal5

**Comment by shaypal5** [comment]
Oh, right! Yes, there is. It's just a different pipeline stage, [`ApplyToRows`](https://pdpipe.readthedocs.io/en/latest/reference/col_generation/#pdpipe.col_generation.ApplyToRows) ([read the docs here](https://pdpipe.readthedocs.io/en/latest/reference/col_generation/#pdpipe.col_generation.ApplyToRows)). This will give you what you want:

```python
pipeline = pdp.PdPipeline([
    pdp.ApplyToRows(
        func=lambda x:(x['A']*5) if x['A']>2 else x['A']*x['B'],
        colname='col_2',
    ),
])
```

<img width="653" alt="image" src="https://user-images.githubusercontent.com/917954/155891097-17acccdc-0efb-41b0-a347-d3519a6c1e39.png">

**Comment by shaypal5** [comment]
Again, if you want the stage to be serializble/pickle-able you need to use a properly-defined function, and not a lambda. :)
