### ISSUE TITLE
sklearn still required at import time from skintegrate module

### ISSUE THREAD

**Issue by daf** [pdpipe/pdpipe#92]
Installing pdpipe 0.2.1 without the optional dependencies sklearn and nltk will error on `import pdpipe` due to the missing sklearn dependency.  Looks like pdpipe's `__init__.py` does try/except/warn guarding for both [sklearn ](https://github.com/pdpipe/pdpipe/blob/d3d7ba600f14a158c8ea34d7e965f533b237e144/pdpipe/__init__.py#L77-L92) and [nltk](https://github.com/pdpipe/pdpipe/blob/d3d7ba600f14a158c8ea34d7e965f533b237e144/pdpipe/__init__.py#L94-L111), but the [import of skintegrate](https://github.com/pdpipe/pdpipe/blob/d3d7ba600f14a158c8ea34d7e965f533b237e144/pdpipe/__init__.py#L119) does not have this import guard.  Shouldn't it?  Otherwise documentation is not quite in line.

The import looks like it was introduced in d00e738c5c82d30be5d7d6bb03e7f821adb2231a.

**Comment by shaypal5** [comment]
Thank you so much for catching this!
Closed in release `v0.2.2`.
